[package]
name = "rust-egui-drafts"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
eframe = "0.32.0"
nutype = "0.6.2"
ropey = "1.6.1"
serde = "1.0.219"
sqlx = "0.8.6"
thiserror = "2.0.14"
uuid = "1.18.0"
