[package]
name = "tasks-example-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"]}
tracing = "0.1.41"
thiserror = { version = "2.0.11" }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
